#!/bin/sh

# this script is likely to return error if multiple processes access it at one time.

set -e

filename="exclusive.resource"
for i in $(seq 1 10); do
  echo "test" >"${filename}"
  cat "${filename}" >/dev/null
  rm "${filename}"
done
